apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret-config
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA6h7VBIPMtRqKjxH7iizJr+Gyq2X1HeS7s1w0/rtJL5OqMx41PsAECNgeGkIu5wF2MQLUxDwRW+bgHoXFeINnycTp5OLemMIXpWaFi1YsQbqOHpzcQQzSjJW/Lrbh5MCSVmH+e5O0j2n7EjmqW8hTF1JKZz/yfBH8iBhw4YFmu+R8zbDaN/3UJgcOzMgtpOir3zG6alaLyhbcFszkzLKjXw3qqH+rSlLfonRf+uj90DXi9C3d6svOJemvr845nqW1pevwY3WYs216msVmQ1e84sltMp2fcg+tzDISFcIEttSH0yC1z/EwNY8eHdCrjDdPbt09zcv2hJXHFCWyMcIaXF/8TAiB248ch0MfuPjUdiOGR7+VezSLL5tShUyvzJWNTstQZ0+1PH7bCM6qfyMI6cjduW/essbtkwilJ3wXaKKfQBZJu6KTnG5Obg9UBhqV98xULw480DLkDCrK/8TLFfqFtrm7+ku+KkHpiFSdVINYh96oGDt7/pBWUhugbFHO7RIkfu9O/WJoS0YLEY2ulPFp1ji0bswWE/Y3kZ2wNCEyk1lk/CikCx7x3pLiwLNwZ/tDrHDJ7dQwboaJZaNIisbXpkJrCSV48/Pox6ES8DZW3sIky2q3zY5RAqp75cB5D/Ki6E7p+WQTpjQPkdmFKdNIFHdO7/Z49ipmeVLBesyO/vFPMpW7lOxPYVf3PipgdEEgkwuaBBWVq9w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: postgres-secret-config
      namespace: default
    type: Opaque

