apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: gmhafiz/web:b169cbaecb549b11f5597ef6dd2f7647fd1133cc
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          name: web
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: web
